import { Injectable } from '@angular/core';
import { Tipologia } from './tipologia';
import { Categoria } from './categoria';
import { Provincia } from './provincia';
import { Regione } from './regioni';

@Injectable()
export class MyDataService {
  getTipologia() {
    return [
    
     new Tipologia(1, 'Lavori' ),
     new Tipologia(2, 'Servizi' ),
     new Tipologia(3, 'Forniture' )
    ];
  }

  getCategoria() {
    return [
		new Categoria('OG1', 1, 'OG1 (Edifici civili e industriali)' ),
		new Categoria('OG2', 1, 'OG2 (Restauro e manutenzione dei beni immobili sottoposti a tutela)' ),
		new Categoria('OG3', 1, 'OG3 (Strade, autostrade, ponti, viadotti, ferrovie, metropolitane)' ),
		new Categoria('OG4', 1, 'OG4 (Opere darte nel sottosuolo)' ),
		new Categoria('OG5', 1, 'OG5 (Dighe)' ),
		new Categoria('OG6', 1, 'OG6 (Acquedotti, gasdotti, oleodotti, opere di irrigazione e di evacuazione)' ),
		new Categoria('OG7', 1, 'OG7 (Opere marittime e lavori di dragaggio)' ),
		new Categoria('OG8', 1, 'OG8 (Opere fluviali, di difesa, di sistemazione idraulica e di bonifica)' ),
		new Categoria('OG9', 1, 'OG9 (Impianti per la produzione di energia elettrica)' ),
		new Categoria('OG10', 1, 'OG10 (Impianti per la trasformazione alta/media tensione e e per la distribuzione di energia elettrica in corrente alternata e continua ed impianti di pubblica illuminazione)' ),
		new Categoria('OG11', 1, 'OG11 (Impianti tecnologici)' ),
		new Categoria('OG12', 1, 'OG12 (Opere ed impianti di bonifica e protezione ambiente)' ),
		new Categoria('OG13', 1, 'OG13 (Opere di ingegneria naturalistica)' ),
		new Categoria('OS1', 1, 'OS1 (Lavori in terra)' ),
		new Categoria('OS2-A', 1, 'OS2-A (Superfici decorate di beni immobili del patrimonio culturale e beni culturali mobili di interesse storico, artistico, archeologico ed etnoantropologico)' ),
		new Categoria('OS2-B', 1, 'OS2-B (Beni culturali mobili di interesse archivistico e librario)' ),
		new Categoria('OS3', 1, 'OS3 (Impianti idrico-sanitario, cucine, lavanderie)' ),
		new Categoria('OS4', 1, 'OS4 (Impianti elettromeccanici trasportatori)' ),
		new Categoria('OS5', 1, 'OS5 (Impianti pneumatici e antintrusione)' ),
		new Categoria('OS6', 1, 'OS6 (Finiture di opere generali in materiali lignei, plastici, metallici e vetrosi)' ),
		new Categoria('OS7', 1, 'OS7 (Finiture di opere generali di natura edile)' ),
		new Categoria('OS8', 1, 'OS8 (Opere di impermeabilizzazione)' ),
		new Categoria('OS9', 1, 'OS9 (Impianti per la segnaletica luminosa e la sicurezza del traffico)' ),
		new Categoria('OS10', 1, 'OS10 (Segnaletica stradale non luminosa)' ),
		new Categoria('OS11', 1, 'OS11 (Apparecchiature strutturali speciali)' ),
		new Categoria('OS12-A', 1, 'OS12-A (Barriere stradali di sicurezza)' ),
		new Categoria('OS12-B', 1, 'OS12-B (Barriere paramassi, fermaneve e simili)' ),
		new Categoria('OS13', 1, 'OS13 (Strutture prefabbricate in cemento armato)' ),
		new Categoria('OS14', 1, 'OS14 (Impianti di smaltimento e recupero dei rifiuti)' ),
		new Categoria('OS15', 1, 'OS15 (Pulizie di acque marine, lacustri, fluviali)' ),
		new Categoria('OS16', 1, 'OS16 (Impianti per centrali di produzione energia elettrica)' ),
		new Categoria('OS17', 1, 'OS17 (Linee telefoniche ed impianti di telefonia)' ),
		new Categoria('OS18-A', 1, 'OS18-A (Componenti strutturali in acciaio)' ),
		new Categoria('OS18-B', 1, 'OS18-B (Componenti per facciate continue)' ),
		new Categoria('OS19', 1, 'OS19 (Impianti di reti di telecomunicazione e di trasmissione dati)' ),
		new Categoria('OS20-A', 1, 'OS20-A (Rilevamenti topografici)' ),
		new Categoria('OS20-B', 1, 'OS20-B (Indagini geognostiche)' ),
		new Categoria('OS21', 1, 'OS21 (Opere strutturali speciali)' ),
		new Categoria('OS22', 1, 'OS22 (Impianti di potabilizzazione e depurazione)' ),
		new Categoria('OS23', 1, 'OS23 (Demolizione di opere)' ),
		new Categoria('OS24', 1, 'OS24 (Verde e arredo urbano)' ),
		new Categoria('OS25', 1, 'OS25 (Scavi archeologici)' ),
		new Categoria('OS26', 1, 'OS26 (Pavimentazioni e sovrastrutture speciali)' ),
		new Categoria('OS27', 1, 'OS27 (Impianti per la trazione elettrica)' ),
		new Categoria('OS28', 1, 'OS28 (Impianti termici e di condizionamento)' ),
		new Categoria('OS29', 1, 'OS29 (Armamento ferroviario)' ),
		new Categoria('OS30', 1, 'OS30 (Impianti interni elettrici, telefonici, radiotelefonici e televisivi)' ),
		new Categoria('OS31', 1, 'OS31 (Impianti per la mobilita sospesa)' ),
		new Categoria('OS32', 1, 'OS32 (Strutture in legno)' ),
		new Categoria('OS33', 1, 'OS33 (Coperture speciali)' ),
		new Categoria('OS34', 1, 'OS34 (Sistemi antirumore per infrastrutture di mobilita' ),
		new Categoria('OS35', 1, 'OS35 (Interventi a basso impatto ambientale)' ),
		new Categoria('45', 1, 'Lavori di costruzione' ),
		new Categoria('50', 2, 'Servizi di riparazione e manutenzione' ),
		new Categoria('51', 2, 'Servizi di installazione' ),
		new Categoria('55', 2, 'Servizi alberghieri' ),
		new Categoria('60', 2, 'Servizi di trasporto' ),
		new Categoria('63', 2, 'Servizi di supporto ai trasporti' ),
		new Categoria('64', 2, 'Servizi di poste e telecomunicazioni' ),
		new Categoria('65', 2, 'Servizi pubblici' ),
		new Categoria('66', 2, 'Servizi finanziari e assicurativi' ),
		new Categoria('70', 2, 'Servizi immobiliari' ),
		new Categoria('71', 2, 'Servizi architettonici e ingegneria ' ),
		new Categoria('72', 2, 'Servizi informatici' ),
		new Categoria('73', 2, 'Servizi di ricerca e sviluppo' ),
		new Categoria('75', 2, 'Servizi di pubblica amministrazione' ),
		new Categoria('76', 2, 'Servizi industria petrolifera' ),
		new Categoria('77', 2, 'Servizi agricoltura' ),
		new Categoria('79', 2, 'Servizi per le imprese' ),
		new Categoria('80', 2, 'Servizi di istruzione e formazione' ),
		new Categoria('85', 2, 'Servizi sanitari' ),
		new Categoria('90', 2, 'Servizi ambientali' ),
		new Categoria('92', 2, 'Servizi ricreativi, culturali e sportivi' ),
		new Categoria('98', 2, 'Altri servizi' ),
		new Categoria('03', 3, 'Prodotti dell agricoltura, allevamento, pesca' ),
		new Categoria('09', 3, 'Prodotti derivati' ),
		new Categoria('14', 3, 'Prodotti minerari' ),
		new Categoria('15', 3, 'Prodotti alimentari' ),
		new Categoria('16', 3, 'Macchinari agricoli' ),
		new Categoria('18', 3, 'Prodotti indumenti' ),
		new Categoria('19', 3, 'Materiali cuoio-tessili-plastica-gomma ' ),
		new Categoria('22', 3, 'Stampati e prodotti affini' ),
		new Categoria('24', 3, 'Sostanze chimiche' ),
		new Categoria('30', 3, 'Macchine per ufficio e PC' ),
		new Categoria('31', 3, 'Macchine di consumo ' ),
		new Categoria('32', 3, 'Attrezzature telecomunicazione' ),
		new Categoria('33', 3, 'Apparecchiature mediche e prodotti farmaceutici' ),
		new Categoria('34', 3, 'Attrezzature di trasporto e prodotti ausiliari per il trasporto' ),
		new Categoria('35', 3, 'Attrezzature di sicurezza, antincendio, per la polizia e di ' ),
		new Categoria('37', 3, 'Strumenti musicali, articoli sportivi, giochi, giocattoli, ' ),
		new Categoria('38', 3, 'Attrezzature da laboratorio, ottiche e di precisione' ),
		new Categoria('39', 3, 'Mobili, arredamento, apparecchi ' ),
		new Categoria('41', 3, 'Acqua captata e depurata' ),
		new Categoria('42', 3, 'Macchinari industriali' ),
		new Categoria('43', 3, 'Macchine per l industria mineraria, lo scavo di cave, ' ),
		new Categoria('44', 3, 'Strutture e materiali per costruzione, prodotti ausiliari per ' ),
		new Categoria('48', 3, 'Pacchetti software e sistemi di informazione' )
    ];
  }

  getRegioni(){
  	return [
        new Regione(2,  "Abruzzo" ),
        new Regione(3,  "Basilicata" ),
        new Regione(7,  "Calabria" ),
        new Regione(8,  "Campania" ),
        new Regione(14,  "Emilia-Romagna" ),
        new Regione(15,  "Friuli-Venezia Giulia" ),
        new Regione(9,  "Lazio" ),
        new Regione(18,  "Liguria" ),
        new Regione(19,  "Lombardia" ),
        new Regione(1,  "Marche" ),
        new Regione(4,  "Molise" ),
		new Regione(13,  "Piemonte" ),
		new Regione(6,  "Puglia" ),
		new Regione(10,  "Sardegna" ),
		new Regione(11,  "Sicilia" ),
		new Regione(12,  "Toscana" ),
		new Regione(5,  "Trentino-Alto Adige" ),
		new Regione(20,  "Umbria" ),
		new Regione(16,  "Valle d'Aosta" ),
		new Regione(17,  "Veneto" ),		
  	];
  }

  getProvincia() {
    return [
		new Provincia("AG", 11, "Agrigento" ),
		new Provincia("AL", 13, "Alessandria" ),
		new Provincia("AN", 1, "Ancona" ),
		new Provincia("AO", 16, "Aosta" ),
		new Provincia("AR", 12, "Arezzo" ),
		new Provincia("AP", 1, "Ascoli Piceno" ),
		new Provincia("AT", 13, "Asti" ),
		new Provincia("AV", 8, "Avellino" ),
		new Provincia("BA", 6, "Bari" ),
		new Provincia("BT", 6, "Barletta" ),
		new Provincia("BL", 17, "Belluno" ),
		new Provincia("BN", 8, "Benevento" ),
		new Provincia("BG", 19, "Bergamo" ),
		new Provincia("BI", 13, "Biella" ),
		new Provincia("BO", 14, "Bologna" ),
		new Provincia("BZ", 5, "Bolzano" ),
		new Provincia("BS", 19, "Brescia" ),
		new Provincia("BR", 6, "Brindisi" ),
		new Provincia("CA", 10, "Cagliari" ),
		new Provincia("CL", 11, "Caltanissetta" ),
		new Provincia("CB", 4, "Campobasso" ),
		new Provincia("CI", 10, "Carbonia Iglesias" ),
		new Provincia("CE", 8, "Caserta" ),
		new Provincia("CT", 11, "Catania" ),
		new Provincia("CZ", 7, "Catanzaro" ),
		new Provincia("CH", 2, "Chieti" ),
		new Provincia("CO", 19, "Como" ),
		new Provincia("CS", 7, "Cosenza" ),
		new Provincia("CR", 19, "Cremona" ),
		new Provincia("KR", 7, "Crotone" ),
		new Provincia("CN", 13, "Cuneo" ),
		new Provincia("EN", 11, "Enna" ),
		new Provincia("FM", 1, "Fermo" ),
		new Provincia("FE", 14, "Ferrara" ),
		new Provincia("FI", 12, "Firenze" ),
		new Provincia("FG", 6, "Foggia" ),
		new Provincia("FC", 14, "Forlì Cesena" ),
		new Provincia("FR", 9, "Frosinone" ),
		new Provincia("GE", 18, "Genova" ),
		new Provincia("GO", 15, "Gorizia" ),
		new Provincia("GR", 12, "Grosseto" ),
		new Provincia("IM", 18, "Imperia" ),
		new Provincia("IS", 4, "Isernia" ),
		new Provincia("AQ", 2, "L'Aquila" ),
		new Provincia("SP", 18, "La Spezia" ),
		new Provincia("LT", 9, "Latina" ),
		new Provincia("LE", 6, "Lecce" ),
		new Provincia("LC", 19, "Lecco" ),
		new Provincia("LI", 12, "Livorno" ),
		new Provincia("LO", 19, "Lodi" ),
		new Provincia("LU", 12, "Lucca" ),
		new Provincia("MC", 1, "Macerata" ),
		new Provincia("MN", 19, "Mantova" ),
		new Provincia("MS", 12, "Massa Carrara" ),
		new Provincia("MT", 3, "Matera" ),
		new Provincia("VS", 10, "Medio Campidano" ),
		new Provincia("ME", 11, "Messina" ),
		new Provincia("MI", 19, "Milano" ),
		new Provincia("MO", 14, "Modena" ),
		new Provincia("MB", 19, "Monza Brianza" ),
		new Provincia("NA", 8, "Napoli" ),
		new Provincia("NO", 13, "Novara" ),
		new Provincia("NU", 10, "Nuoro" ),
		new Provincia("OG", 10, "Ogliastra" ),
		new Provincia("OT", 10, "Olbia Tempio" ),
		new Provincia("OR", 10, "Oristano" ),
		new Provincia("PD", 17, "Padova" ),
		new Provincia("PA", 11, "Palermo" ),
		new Provincia("PR", 14, "Parma" ),
		new Provincia("PV", 19, "Pavia" ),
		new Provincia("PG", 20, "Perugia" ),
		new Provincia("PU", 1, "Pesaro Urbino" ),
		new Provincia("PE", 2, "Pescara" ),
		new Provincia("PC", 14, "Piacenza" ),
		new Provincia("PI", 12, "Pisa" ),
		new Provincia("PT", 12, "Pistoia" ),
		new Provincia("PN", 15, "Pordenone" ),
		new Provincia("PZ", 3, "Potenza" ),
		new Provincia("PO", 12, "Prato" ),
		new Provincia("RG", 11, "Ragusa" ),
		new Provincia("RA", 14, "Ravenna" ),
		new Provincia("RC", 7, "Reggio Calabria" ),
		new Provincia("RE", 14, "Reggio Emilia" ),
		new Provincia("RI", 9, "Rieti" ),
		new Provincia("RN", 14, "Rimini" ),
		new Provincia("RM", 9, "Roma" ),
		new Provincia("RO", 17, "Rovigo" ),
		new Provincia("SA", 8, "Salerno" ),
		new Provincia("SS", 10, "Sassari" ),
		new Provincia("SV", 18, "Savona" ),
		new Provincia("SI", 12, "Siena" ),
		new Provincia("SR", 11, "Siracusa" ),
		new Provincia("SO", 19, "Sondrio" ),
		new Provincia("TA", 6, "Taranto" ),
		new Provincia("TE", 2, "Teramo" ),
		new Provincia("TR", 20, "Terni" ),
		new Provincia("TO", 13, "Torino" ),
		new Provincia("TP", 11, "Trapani" ),
		new Provincia("TN", 5, "Trento" ),
		new Provincia("TV", 17, "Treviso" ),
		new Provincia("TS", 15, "Trieste" ),
		new Provincia("UD", 15, "Udine" ),
		new Provincia("VA", 19, "Varese" ),
		new Provincia("VE", 17, "Venezia" ),
		new Provincia("VB", 13, "Verbania" ),
		new Provincia("VC", 13, "Vercelli" ),
		new Provincia("VR", 17, "Verona" ),
		new Provincia("VV", 7, "Vibo Valentia" ),
		new Provincia("VI", 17, "Vicenza" ),
		new Provincia("VT", 9, "Viterbo" ),
    ];
  }

}

